apiVersion: v1
kind: Secret
metadata:
  name: postgresql-secret
type: Opaque
data:
  password: {{ .Values.auth.password | b64enc }}
  username: {{ .Values.auth.username | b64enc }}
  database: {{ .Values.auth.database | b64enc }}
